const Utils = require('./utils');
const description = `
/***********************/
/*     PROBLEM 045     */
/***********************/
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  		1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
`;

function job(file) {

	let i = 143 + 1,
		hi = Utils.hexagon(i);
	while (!Utils.isPentagon(hi) && !Utils.isTriangle(hi)) {
		hi += Utils.toNextHexagon(++i);
	}
	return hi;

}

module.exports = {
	d: description,
	p: null,
	f: job
}